/**
 * @file icons.h
 * @brief Declarations for the window icons embedded into the binary.
 *
 * The actual icon data is generated by cmake/embed-icons.cmake from the
 * PNG files in icons/ at build time, so the statically linked executable
 * carries its own window icon and needs no external files.
 */

#pragma once

namespace ui::icons
{

/**
 * @brief One embedded icon: a PNG file decoded at runtime with stb_image.
 */
struct EmbeddedIcon
{
  int size;                          ///< Icon edge length in pixels.
  const unsigned char* data;         ///< Raw PNG file bytes.
  unsigned int data_size;            ///< Number of bytes in \ref data.
};

/// Array of embedded icons, ordered by increasing size.
extern const EmbeddedIcon embedded_icons[];

/// Number of entries in \ref embedded_icons.
extern const int embedded_icon_count;

} // namespace ui::icons
