# Embeds the PNG icons from icons/ into a generated C++ source file.
#
# Usage (from CMake):
#   cmake -DOUT=<output.cpp> -DICON_DIR=<icons dir> -P embed-icons.cmake

set(ICON_SIZES 16 32 48 64 128 256)
list(LENGTH ICON_SIZES ICON_COUNT)

set(content "// Auto-generated by cmake/embed-icons.cmake - DO NOT EDIT.\n")
string(APPEND content "#include \"ui/icons.h\"\n\nnamespace ui::icons\n{\n")

foreach(size IN LISTS ICON_SIZES)
  set(png "${ICON_DIR}/machina-icon-${size}.png")
  if(NOT EXISTS "${png}")
    message(FATAL_ERROR "Icon not found: ${png}")
  endif()
  file(READ "${png}" hex HEX)
  string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
  string(APPEND content "const unsigned char icon_${size}_data[] = {\n${bytes}\n};\n\n")
endforeach()

string(APPEND content "const EmbeddedIcon embedded_icons[] = {\n")
foreach(size IN LISTS ICON_SIZES)
  string(APPEND content "  {${size}, icon_${size}_data, sizeof(icon_${size}_data)},\n")
endforeach()
string(APPEND content "};\n\n")
string(APPEND content "const int embedded_icon_count = ${ICON_COUNT};\n")
string(APPEND content "\n} // namespace ui::icons\n")

file(WRITE "${OUT}" "${content}")
